/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'submittedAt' : bigint,
  'tournamentId' : bigint,
  'playerPrincipal' : Principal,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Tournament {
  'id' : bigint,
  'endDate' : bigint,
  'name' : string,
  'description' : string,
  'roomPassword' : [] | [string],
  'roomVisibilityMinutes' : [] | [bigint],
  'gameType' : string,
  'maxParticipants' : bigint,
  'entryFee' : bigint,
  'roomId' : [] | [string],
  'prizePool' : bigint,
  'startDate' : bigint,
}
export interface TournamentUpdate {
  'id' : bigint,
  'endDate' : [] | [bigint],
  'name' : [] | [string],
  'description' : [] | [string],
  'roomPassword' : [] | [string],
  'roomVisibilityMinutes' : [] | [bigint],
  'gameType' : [] | [string],
  'maxParticipants' : [] | [bigint],
  'entryFee' : [] | [bigint],
  'roomId' : [] | [string],
  'prizePool' : [] | [bigint],
  'startDate' : [] | [bigint],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserPreferences {
  'emailNotifications' : boolean,
  'publicProfile' : boolean,
  'pushNotifications' : boolean,
}
export interface UserProfile {
  'bio' : string,
  'country' : string,
  'displayName' : string,
  'email' : string,
  'preferences' : UserPreferences,
  'avatarUrl' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'approvePayment' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProfile' : ActorMethod<[UserProfile], undefined>,
  'createTournament' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      [] | [string],
      [] | [string],
      [] | [bigint],
    ],
    bigint
  >,
  'deleteOrCloseTournament' : ActorMethod<[bigint], undefined>,
  'deleteProfile' : ActorMethod<[], undefined>,
  'getAdmins' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSuperAdmin' : ActorMethod<[], [] | [Principal]>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProfileComplete' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isSuperAdmin' : ActorMethod<[Principal], boolean>,
  'listPaymentsByTournament' : ActorMethod<[bigint], Array<Payment>>,
  'listPendingPayments' : ActorMethod<[], Array<Payment>>,
  'listTournaments' : ActorMethod<[], Array<Tournament>>,
  'rejectPayment' : ActorMethod<[bigint], undefined>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRoomCredentials' : ActorMethod<
    [bigint, [] | [string], [] | [string], [] | [bigint]],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitPayment' : ActorMethod<[bigint], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTournament' : ActorMethod<[TournamentUpdate], undefined>,
  'uploadResults' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];